### ISSUE TITLE
Back button doesn't do anything

### ISSUE THREAD

**Issue by geoffyuen** [terabaud/eleventy-mini-spa#1]
Visiting the demo site: https://terabaud.github.io/eleventy-mini-spa/ 
and browsing thru the pages. If you click the back button the page doesn't change.

**Comment by kylesloper** [comment]
This is would be brilliant if this could be fixed. @terabaud do we have an update on this?

**Comment by learosema** [comment]
Right, this needs to be fixed, a popstate event listener is missing. Will take care of it tomorrow.

**Comment by learosema** [comment]
I updated the mini-spa.js file so it now handles the back button. 

https://github.com/terabaud/eleventy-mini-spa/blob/main/src/js/mini-spa.js 
The demo link should now work: https://terabaud.github.io/eleventy-mini-spa/

**Comment by kylesloper** [comment]
Thankyou very much. Great plugin ❤
